import type { KanbanTask } from "@/types/kanban";

export function generateMockTasks(): KanbanTask[] {
  return [
    {
      id: "11",
      title: "New Dashboard design.",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla soluta consectetur sit amet elit dolor sit amet.",
      status: "new",
      createdDate: "28 May",
      daysLeft: 2,
      labels: ["UI/UX"],
      likes: 12,
      comments: 2,
      assignees: [1, 2, 3, 4],
      hasMore: false,
    },
    {
      id: "05",
      title: "Marketing next projects.",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla soluta consectetur sit amet elit dolor sit amet.",
      status: "new",
      createdDate: "30 May",
      daysLeft: 2,
      labels: ["Marketing", "Finance"],
      likes: 40,
      comments: 8,
      assignees: [2, 5],
      hasMore: false,
    },
    {
      id: "08",
      title: "New Project Discussion.",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla soluta",
      status: "new",
      createdDate: "02 Jun",
      daysLeft: 1,
      labels: ["Designing"],
      likes: 0,
      comments: 0,
      assignees: [],
      hasMore: true,
    },
    {
      id: "07",
      title: "Adding Authentication Pages.",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla soluta",
      status: "todo",
      createdDate: "01 Jun",
      daysLeft: 10,
      labels: ["Admin", "Authentication"],
      likes: 8,
      comments: 2,
      assignees: [1, 2, 3],
      hasMore: false,
    },
    {
      id: "15",
      title: "New Project Discussion.",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla soluta",
      status: "todo",
      createdDate: "05 Jun",
      daysLeft: 14,
      labels: ["Planning"],
      likes: 17,
      comments: 8,
      assignees: [1, 2, 3, 4],
      image: "/placeholder.svg?keyboard",
      hasMore: true,
    },
    {
      id: "13",
      title: "Create Calendar & Mail pages.",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla soluta",
      status: "ongoing",
      createdDate: "02 Jun",
      daysLeft: 5,
      labels: ["UI Design", "Development"],
      likes: 5,
      comments: 13,
      assignees: [7, 8],
      hasMore: false,
    },
    {
      id: "09",
      title: "Project design Figma,Sketch.",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla soluta",
      status: "ongoing",
      createdDate: "03 Jun",
      daysLeft: 12,
      labels: ["Product"],
      likes: 2,
      comments: 0,
      assignees: [6],
      hasMore: true,
    },
    {
      id: "15",
      title: "Design Architecture strategy.",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla soluta",
      status: "review",
      createdDate: "05 Jun",
      daysLeft: 14,
      labels: ["Review"],
      likes: 9,
      comments: 35,
      assignees: [1, 2, 3],
      image: "/placeholder.svg?design",
      hasMore: true,
    },
    {
      id: "04",
      title: "Sash project update.",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla soluta",
      status: "completed",
      createdDate: "12 Jun",
      daysLeft: 0,
      labels: ["UI/UX"],
      likes: 18,
      comments: 3,
      assignees: [1, 2],
      hasMore: false,
    },
    {
      id: "10",
      title: "React JS new version update.",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla soluta",
      status: "completed",
      createdDate: "10 Jun",
      daysLeft: 0,
      labels: ["Development"],
      likes: 22,
      comments: 12,
      assignees: [1, 2, 3],
      hasMore: true,
    },
    {
      id: "19",
      title: "New Project Discussion.",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla soluta",
      status: "completed",
      createdDate: "07 Jun",
      daysLeft: 0,
      labels: ["Discussion"],
      likes: 0,
      comments: 0,
      assignees: [1],
      hasMore: true,
    },
  ];
}
